### ISSUE TITLE
Workflow failing after updating settings

### ISSUE THREAD

**Issue by GaslightGod** [marcizhu/readme-chess#17]
I've updated token settings to read and write but it's still giving me the same 403 error
![error workflow](https://github.com/marcizhu/readme-chess/assets/60765944/cbedd4b1-21ed-4d00-b5b6-453cae785c99)
![error workflow 2](https://github.com/marcizhu/readme-chess/assets/60765944/8e455ed7-63ed-400a-9e40-cba897a6769f)

**Comment by marcizhu** [comment]
@GaslightGod I had a look and I see you created a _template_, not a regular repository. I'm not sure if this is the cause of your problem but I would start by changing that. I've never seen a workflow even being executed on a template so I wouldn't be surprised if GitHub disallowed pushing from workflows on template repos.

**Comment by GaslightGod** [comment]
I generated a repository from the template. Should I just clone the repository and upload? Unless I'm misunderstanding the use of the template built-in it should generate a new repository based off yours.

**Comment by marcizhu** [comment]
You should create a repo from this template, but you should NOT make your repo a template. Keep it a "normal" repository. Currently it's marked as a template:
<img width="270" alt="image" src="https://github.com/marcizhu/readme-chess/assets/6199781/a3a3f0c9-682b-46ef-b095-2779a36d662e">

You can change this on your repo settings.

**Comment by GaslightGod** [comment]
After switching the issue persists privileges are still escalated

**Comment by marcizhu** [comment]
Can you double-check under Settings > Actions > General that your Workflow permissions look like this?
<img width="785" alt="image" src="https://github.com/marcizhu/readme-chess/assets/6199781/7d11769e-dac4-4d99-b3a5-bd25458ace0f">

This is the only thing that comes to mind, I don't see why else it would fail.

**Comment by marcizhu** [comment]
My repo has been working fine for the last 3+ years so I don't think this is a general issue with workflows, nor anything deprecated in the YAML files. I use exactly the same configuration available in this repo so it should work for you as well...

**Comment by marcizhu** [comment]
@GaslightGod I managed to reproduce your issue and it should be fixed now as of the latest commit in the master branch. Could you re-create your repo to test it? Alternatively, add `contents: write` under the permissions section in your Chess.yml workflow file:

```yml
name: Chess

on:
  issues:
    types: [opened]

jobs:
  move:
    permissions:
      issues: write
      contents: write
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'Chess:')
...
```

Lets keep this issue open until we find a solution since it looks like a genuine bug to me.

**Comment by GaslightGod** [comment]
Happy to report that it is working perfectly now! Thanks for all the help and the quick patch

**Comment by marcizhu** [comment]
Happy to help! It was a quick one 😄
