### ISSUE TITLE
"Start new game" is considered as a move

### ISSUE THREAD

**Issue by tb148** [marcizhu/readme-chess#3]
So the person who started the game cannot make the 1st move

**Comment by marcizhu** [comment]
I agree, starting a new game shouldn't count as a move. Give me a few minutes so I can implement (and test) this

**Comment by marcizhu** [comment]
This should be fixed now. I'm gonna push the changes to [marcizhu/marcizhu](https://github.com/marcizhu/marcizhu) and this should be done!

Thanks for the report 👍🏻 😄

**Comment by marcizhu** [comment]
@tb148 you can either add the changes manually or delete the repo and re-create it. Either one should do :D
