### ISSUE TITLE
Game wouldn't end

### ISSUE THREAD

**Issue by afanasy** [marcizhu/readme-chess#5]
Black move, white king is attacked by the black queen, the game should end:
<img width="491" alt="Screenshot 2022-07-15 at 16 21 15" src="https://user-images.githubusercontent.com/677646/179183721-91cc153e-671b-4da7-a305-66bdb51ffd02.png">
https://github.com/import-brain

**Comment by marcizhu** [comment]
The white king is not attacked by black's queen. Black's queen is on D8, the starting square. The piece on H2 is a rook, so it is not giving check to white's king at all. Furthermore, the rook on H2 is not defended by any other black piece, so even if it were a queen, the white king could simply capture the queen.

It is not game over. Keep playing! And have fun 😄

**Comment by marcizhu** [comment]
Stockfish also thinks that this position is completely fine. I hope these icons clear out the doubt on which pieces are which:
<img width="617" alt="image" src="https://user-images.githubusercontent.com/6199781/179250865-0a424382-6d49-4bf7-b7e1-1d36251c304a.png">

And as I said, even if it were a queen, white's king could simply take (in fact that was the best move):
<img width="618" alt="image" src="https://user-images.githubusercontent.com/6199781/179251217-d453fd87-88e1-43fe-9082-a21a33a87191.png">

**Comment by afanasy** [comment]
Got confused by the shapes, thank you for the review @marcizhu!
